import { Inter } from 'next/font/google'
import './globals.css'
import Toast from '@/component/Toast'
import FacebookPixel from '@/utils/facebookPixel'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <FacebookPixel />
      <Toast />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
