import { Inter } from 'next/font/google'
import './globals.css'
import Toast from '@/component/Toast'
import { GoogleTagManager } from '@next/third-parties/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="GTM-N9Q66F29" />
      <Toast />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
